# version: '3'

# services:
#   # Mongo db
#   mongo:
#     image: mongo
#     restart: always
#     env_file: ./.env
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
#       - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
#     ports:
#       - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
#     volumes:
#       - ./database:/data/db

#   # API - devops project
#   devops:
#     build:
#       context: /devops
#       dockerfile: Dockerfile
#     env_file: ./.env
#     ports:
#       - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#     environment:
#       - DB_HOST=mongodb
#       - DB_USER=$MONGODB_USER
#       - DB_PASSWORD=$MONGODB_PASSWORD
#       - DB_NAME=$MONGODB_DATABASE
#       - DB_PORT=$MONGODB_DOCKER_PORT
#     volumes:
#       - ./devops:/app
#     depends_on:
#       - mongo
# version: '3'

# services:
#   # API - API
#   devops:
#     build:
#       context: /devops
#       dockerfile: Dockerfile
#     ports:
#       - "12345:3000"
#     environment:
#       - MONGO_USERNAME=DanielIne
#       - MONGO_PASSWORD=DanielIne123
#       - MONGO_URL=mongodb://mongo:27017/mongodb4devopsapi
#     volumes:
#       - ./devops:/app
#     depends_on:
#       - mongo

#   # Database - Mongo DB
#   mongo:
#     image: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: DanielIne
#       MONGO_INITDB_ROOT_PASSWORD: DanielIne123
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./database:/data/db

version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build: 
      context: /devops
      dockerfile: /Dockerfile
    container_name: devops_api
    ports:
      - "3000:3000"
    environment:
     - MONGO_URI=mongodb://root:example@mongo_db:27017/
    depends_on:
      - mongodb