name: API Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and run tests
        working-directory: ./api
        run: |
          npm install
          npm test

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
            working-directory: ./api